// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: legate_test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Unary messages
type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_legate_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_legate_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Client streaming messages
type CollectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectRequest) Reset() {
	*x = CollectRequest{}
	mi := &file_legate_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectRequest) ProtoMessage() {}

func (x *CollectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectRequest.ProtoReflect.Descriptor instead.
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{2}
}

func (x *CollectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CollectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`    // All received data joined with "|"
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // Number of messages received
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectResponse) Reset() {
	*x = CollectResponse{}
	mi := &file_legate_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectResponse) ProtoMessage() {}

func (x *CollectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectResponse.ProtoReflect.Descriptor instead.
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{3}
}

func (x *CollectResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CollectResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Server streaming messages
type ExpandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`  // Number of responses to generate
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"` // Prefix for each response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_legate_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{4}
}

func (x *ExpandRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ExpandRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

type ExpandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // prefix + ":" + sequence_number
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_legate_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{5}
}

func (x *ExpandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExpandResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Bidirectional streaming messages
type BiEchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BiEchoRequest) Reset() {
	*x = BiEchoRequest{}
	mi := &file_legate_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiEchoRequest) ProtoMessage() {}

func (x *BiEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiEchoRequest.ProtoReflect.Descriptor instead.
func (*BiEchoRequest) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{6}
}

func (x *BiEchoRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BiEchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // "N:original_data" where N is 0-indexed sequence
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BiEchoResponse) Reset() {
	*x = BiEchoResponse{}
	mi := &file_legate_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiEchoResponse) ProtoMessage() {}

func (x *BiEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_legate_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiEchoResponse.ProtoReflect.Descriptor instead.
func (*BiEchoResponse) Descriptor() ([]byte, []int) {
	return file_legate_test_proto_rawDescGZIP(), []int{7}
}

func (x *BiEchoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BiEchoResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_legate_test_proto protoreflect.FileDescriptor

const file_legate_test_proto_rawDesc = "" +
	"\n" +
	"\x11legate_test.proto\x12\vlegate.test\"!\n" +
	"\vEchoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\"\n" +
	"\fEchoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"$\n" +
	"\x0eCollectRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\";\n" +
	"\x0fCollectResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"=\n" +
	"\rExpandRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\fR\x06prefix\"@\n" +
	"\x0eExpandResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\"#\n" +
	"\rBiEchoRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"@\n" +
	"\x0eBiEchoResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence2\x9e\x02\n" +
	"\vTestService\x12;\n" +
	"\x04Echo\x12\x18.legate.test.EchoRequest\x1a\x19.legate.test.EchoResponse\x12F\n" +
	"\aCollect\x12\x1b.legate.test.CollectRequest\x1a\x1c.legate.test.CollectResponse(\x01\x12C\n" +
	"\x06Expand\x12\x1a.legate.test.ExpandRequest\x1a\x1b.legate.test.ExpandResponse0\x01\x12E\n" +
	"\x06BiEcho\x12\x1a.legate.test.BiEchoRequest\x1a\x1b.legate.test.BiEchoResponse(\x010\x01B Z\x1elegate/tests/integration/go/pbb\x06proto3"

var (
	file_legate_test_proto_rawDescOnce sync.Once
	file_legate_test_proto_rawDescData []byte
)

func file_legate_test_proto_rawDescGZIP() []byte {
	file_legate_test_proto_rawDescOnce.Do(func() {
		file_legate_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_legate_test_proto_rawDesc), len(file_legate_test_proto_rawDesc)))
	})
	return file_legate_test_proto_rawDescData
}

var file_legate_test_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_legate_test_proto_goTypes = []any{
	(*EchoRequest)(nil),     // 0: legate.test.EchoRequest
	(*EchoResponse)(nil),    // 1: legate.test.EchoResponse
	(*CollectRequest)(nil),  // 2: legate.test.CollectRequest
	(*CollectResponse)(nil), // 3: legate.test.CollectResponse
	(*ExpandRequest)(nil),   // 4: legate.test.ExpandRequest
	(*ExpandResponse)(nil),  // 5: legate.test.ExpandResponse
	(*BiEchoRequest)(nil),   // 6: legate.test.BiEchoRequest
	(*BiEchoResponse)(nil),  // 7: legate.test.BiEchoResponse
}
var file_legate_test_proto_depIdxs = []int32{
	0, // 0: legate.test.TestService.Echo:input_type -> legate.test.EchoRequest
	2, // 1: legate.test.TestService.Collect:input_type -> legate.test.CollectRequest
	4, // 2: legate.test.TestService.Expand:input_type -> legate.test.ExpandRequest
	6, // 3: legate.test.TestService.BiEcho:input_type -> legate.test.BiEchoRequest
	1, // 4: legate.test.TestService.Echo:output_type -> legate.test.EchoResponse
	3, // 5: legate.test.TestService.Collect:output_type -> legate.test.CollectResponse
	5, // 6: legate.test.TestService.Expand:output_type -> legate.test.ExpandResponse
	7, // 7: legate.test.TestService.BiEcho:output_type -> legate.test.BiEchoResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_legate_test_proto_init() }
func file_legate_test_proto_init() {
	if File_legate_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_legate_test_proto_rawDesc), len(file_legate_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_legate_test_proto_goTypes,
		DependencyIndexes: file_legate_test_proto_depIdxs,
		MessageInfos:      file_legate_test_proto_msgTypes,
	}.Build()
	File_legate_test_proto = out.File
	file_legate_test_proto_goTypes = nil
	file_legate_test_proto_depIdxs = nil
}
