// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: legate_test.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TestService_Echo_FullMethodName    = "/legate.test.TestService/Echo"
	TestService_Collect_FullMethodName = "/legate.test.TestService/Collect"
	TestService_Expand_FullMethodName  = "/legate.test.TestService/Expand"
	TestService_BiEcho_FullMethodName  = "/legate.test.TestService/BiEcho"
)

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TestService exercises all 4 gRPC patterns for Legate integration testing.
// Uses simple byte payloads for transport-only testing.
type TestServiceClient interface {
	// Unary: Echo back the request with "ECHO:" prefix
	// Request: arbitrary bytes
	// Response: "ECHO:" + request bytes
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Client Streaming: Collect multiple messages, return concatenated result
	// Client sends N messages, server responds with all messages joined with "|"
	Collect(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CollectRequest, CollectResponse], error)
	// Server Streaming: Expand a single request into multiple responses
	// Request contains a count N, server sends N responses numbered 0 to N-1
	Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExpandResponse], error)
	// Bidirectional: Echo each message back immediately with sequence number
	// Each client message gets an immediate response with "N:message" format
	BiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BiEchoRequest, BiEchoResponse], error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, TestService_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) Collect(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CollectRequest, CollectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], TestService_Collect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectRequest, CollectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_CollectClient = grpc.ClientStreamingClient[CollectRequest, CollectResponse]

func (c *testServiceClient) Expand(ctx context.Context, in *ExpandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExpandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[1], TestService_Expand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExpandRequest, ExpandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_ExpandClient = grpc.ServerStreamingClient[ExpandResponse]

func (c *testServiceClient) BiEcho(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BiEchoRequest, BiEchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[2], TestService_BiEcho_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BiEchoRequest, BiEchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_BiEchoClient = grpc.BidiStreamingClient[BiEchoRequest, BiEchoResponse]

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility.
//
// TestService exercises all 4 gRPC patterns for Legate integration testing.
// Uses simple byte payloads for transport-only testing.
type TestServiceServer interface {
	// Unary: Echo back the request with "ECHO:" prefix
	// Request: arbitrary bytes
	// Response: "ECHO:" + request bytes
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	// Client Streaming: Collect multiple messages, return concatenated result
	// Client sends N messages, server responds with all messages joined with "|"
	Collect(grpc.ClientStreamingServer[CollectRequest, CollectResponse]) error
	// Server Streaming: Expand a single request into multiple responses
	// Request contains a count N, server sends N responses numbered 0 to N-1
	Expand(*ExpandRequest, grpc.ServerStreamingServer[ExpandResponse]) error
	// Bidirectional: Echo each message back immediately with sequence number
	// Each client message gets an immediate response with "N:message" format
	BiEcho(grpc.BidiStreamingServer[BiEchoRequest, BiEchoResponse]) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTestServiceServer struct{}

func (UnimplementedTestServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedTestServiceServer) Collect(grpc.ClientStreamingServer[CollectRequest, CollectResponse]) error {
	return status.Error(codes.Unimplemented, "method Collect not implemented")
}
func (UnimplementedTestServiceServer) Expand(*ExpandRequest, grpc.ServerStreamingServer[ExpandResponse]) error {
	return status.Error(codes.Unimplemented, "method Expand not implemented")
}
func (UnimplementedTestServiceServer) BiEcho(grpc.BidiStreamingServer[BiEchoRequest, BiEchoResponse]) error {
	return status.Error(codes.Unimplemented, "method BiEcho not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}
func (UnimplementedTestServiceServer) testEmbeddedByValue()                     {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	// If the following call panics, it indicates UnimplementedTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TestService_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).Collect(&grpc.GenericServerStream[CollectRequest, CollectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_CollectServer = grpc.ClientStreamingServer[CollectRequest, CollectResponse]

func _TestService_Expand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExpandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).Expand(m, &grpc.GenericServerStream[ExpandRequest, ExpandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_ExpandServer = grpc.ServerStreamingServer[ExpandResponse]

func _TestService_BiEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TestServiceServer).BiEcho(&grpc.GenericServerStream[BiEchoRequest, BiEchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TestService_BiEchoServer = grpc.BidiStreamingServer[BiEchoRequest, BiEchoResponse]

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "legate.test.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _TestService_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Collect",
			Handler:       _TestService_Collect_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Expand",
			Handler:       _TestService_Expand_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BiEcho",
			Handler:       _TestService_BiEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "legate_test.proto",
}
